name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repo en el runner
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar la clave SSH
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LINODE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_HOST }} 'echo "SSH conexión exitosa"'

      # Paso 3: Copiar y ejecutar el script desde GitHub runner al VPS
      - name: Run deploy.sh remotely
        run: |
          scp -i ~/.ssh/id_rsa -P ${{ secrets.LINODE_PORT }} scripts/deploy.sh ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_HOST }}:/tmp/deploy.sh
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.LINODE_PORT }} -o StrictHostKeyChecking=no ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_HOST }} "bash /tmp/deploy.sh"
